package edu.cnm.deepdive.vaccpocketkeeper.controller;

import android.os.Bundle;
import android.text.Editable;
import android.text.TextWatcher;
import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.lifecycle.ViewModelProvider;
import com.google.android.material.bottomsheet.BottomSheetDialogFragment;
import edu.cnm.deepdive.vaccpocketkeeper.databinding.FragmentEditDoctorBinding;
import edu.cnm.deepdive.vaccpocketkeeper.model.entity.Doctor;
import edu.cnm.deepdive.vaccpocketkeeper.viewmodel.DoctorViewModel;

public class EditDoctorFragment extends BottomSheetDialogFragment implements TextWatcher {

  private FragmentEditDoctorBinding binding;
  private DoctorViewModel viewModel;
  private long doctorId;
  private Doctor doctor;

  @Override
  public void onCreate(Bundle savedInstanceState) {
    super.onCreate(savedInstanceState);
    EditDoctorFragmentArgs args = EditDoctorFragmentArgs.fromBundle(getArguments()); //generated for us by navigation framework
    doctorId = args.getDoctorId(); //autogenerated getDoctorId from navgraph argument name
  }

  @Override
  public View onCreateView(@NonNull LayoutInflater inflater, ViewGroup container,
      Bundle savedInstanceState) {
    binding = FragmentEditDoctorBinding.inflate(inflater, container, false);
    binding.doctorName.addTextChangedListener(this);
    binding.cancel.setOnClickListener((v) -> dismiss());
    binding.save.setOnClickListener((v) -> {
      doctor.setName(binding.doctorName.getText().toString().trim());
      viewModel.save(doctor);
      dismiss();
    });
    return binding.getRoot();
  }

  @Override
  public void onViewCreated(@NonNull View view, @Nullable Bundle savedInstanceState) {
    super.onViewCreated(view, savedInstanceState);
    viewModel = new ViewModelProvider(this).get(DoctorViewModel.class);
    if (doctorId != 0) { //previous doctor
      //TODO Set doctorID in viewmodel and observe viewmodel.getDoctor()
      //viewModel.getDoctor()
    } else { //new doctor
      doctor = new Doctor();
    }
  }

  @Override
  public void onDestroyView() {
    super.onDestroyView();
    binding = null;
  }

  @Override
  public void beforeTextChanged(CharSequence charSequence, int i, int i1, int i2) {
    //Do nothing.
  }

  @Override
  public void onTextChanged(CharSequence charSequence, int i, int i1, int i2) {
    //Do nothing.
  }

  @Override
  public void afterTextChanged(Editable editable) {
    checkSubmitConditions();
  }

  private void checkSubmitConditions() {
    String doctor = binding.doctorName.getText().toString().trim();
    binding.save.setEnabled(!doctor.isEmpty());
  }
}
